[12|1557819580079|1|INFO       ][FactoryHelper|FactoryHelper.getApplicationVersionFromReleaseFile] : Application version:   Release file: Flux_Release.txt   Version: 2018.1.0.1121 20180629
[13|1557819580281|19|CONFIG     ][ApplicationConfiguration|LookandFeelEnum.setCurrentLookAndFeel] : Applying look&feel: (PLASTIC_3D, com.jgoodies.plaf.plastic.Plastic3DLookAndFeel)
[14|1557819580352|1|CONFIG     ][Application|CoreApplication.internalLaunchApplication] : Application flags:   Debug: false   Advanced: false   Server: false   Batch: false   New project: false
[15|1557819580355|1|CONFIG     ][Application|MainFlux.initEnvironment] : User name: jperalta
[16|1557819580356|1|CONFIG     ][Application|CoreApplication.validateDirectory] : Install directory: C:\Program Files\Altair\2018\flux\Flux\Resources
[17|1557819580356|1|CONFIG     ][Application|CoreApplication.validateDirectory] : User home: C:\Users\jperalta
[18|1557819580356|1|CONFIG     ][Application|CoreApplication.validateDirectory] : Running directory: C:\Users\jperalta\Documents\github_pato\flux\2_int_rotor\1_int_rotor_slotless\8_icems_journal_2018_3d
[19|1557819580357|1|CONFIG     ][Application|CoreApplication.validateDirectory] : Temporary directory: C:\Users\jperalta\AppData\Local\Temp
[20|1557819580357|1|CONFIG     ][Application|MainFlux.initEnvironment] : Environment variable CAO_DEFLAN: 2
[21|1557819580357|1|CONFIG     ][Application|MainFlux.initEnvironment] : Extension directory:   Defined: C:\Program Files\Altair\2018\flux\Flux\extensions   Final: C:\Users\jperalta
[22|1557819580357|1|CONFIG     ][Application|MainFlux.initEnvironment] : Certified overlay directory:   Defined: C:\Program Files\Altair\2018\flux\Flux\Overlays   Final: C:\Program Files\Altair\2018\flux\Flux\Overlays
[23|1557819580358|1|CONFIG     ][Application|MainFlux.initEnvironment] : User overlay directory:   Defined: C:\Program Files\Altair\2018\flux\Extensions\Overlays   Final: C:\Program Files\Altair\2018\flux\Extensions\Overlays
[24|1557819580358|1|CONFIG     ][Application|MainFlux.initEnvironment] : Macro directory:   Defined: C:\Program Files\Altair\2018\flux\Extensions\Macros   Final: C:\Program Files\Altair\2018\flux\Extensions\Macros
[25|1557819580550|1|WARNING    ][Selection|DocumentSelectionManager.attachSelectionClient] : Already attached, client: cad.core.frontal.graphic.view.GraphicViewsManager$EventHandler@376b4233
Loading data model 'Flux_model.stp'
[27|1557819580926|12|INFO       ][Application|CoreApplication$SyncRunnable.run] : Stop application synchronisation thread
Python : @#*C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/Flux3D_log.pyPython : ^&|#! Flux3D 18.1
Recording commands in 'C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/Flux3D_log.py'
 
                                                             FLUX3D_18.1.0 : 3D Finite Element Electromagnetism
                                                                   4096 MiB N. + 127 MiB C. + 2048 MiB J.
                                                                  HWU licensing used: 6200@stilic5.epfl.ch
                                           Build 1806291121 Flux_Release_2018.1 CL15346 Win64 4/8 cores LAIB108233:17304 jperalta
 
09:39:45       0 sec. FLUX3D_18.1.0 kernel initialized
[62315|1557819585673|1|INFO       ][FrontalPreferences|DefaultFrontalPreferencesManager.getApplicationConfiguration] : Loading Frontal ApplicationConfiguration:   Application: Flux3D   Version: 2018.1
[62316|1557819585675|1|INFO       ][ApplicationConfiguration|ApplicationConfiguration.getApplicationConfiguration] : Application: (Flux3D, 2018.1)
[62317|1557819585869|1|CONFIG     ][ApplicationConfiguration|ApplicationConfiguration.updateGroupPreferences] : Application configuration updated:   Application: (Flux3D, 2018.1)   Groups: 6
[62319|1557819586393|19|WARNING    ][Selection|DocumentSelectionManager.attachSelectionClient] : Already attached, client: cad.core.frontal.components.box.frontaldialog.FrontalDialogBoxManager$EventHandler@49aa1d3b

Flux3D (application 2018.1) running

[62328|1557819586499|19|WARNING    ][Selection|DocumentSelectionManager.attachSelectionClient] : Already attached, client: cad.core.frontal.components.tree.TreeManager$EventHandler@1410a137
[62348|1557819587770|1|WARNING    ][Document|Document.updateInstances] : No project loaded
[62354|1557819587797|1|WARNING    ][Document|Document.updateInstances] : No project loaded
Execution of command file 'C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py' in batch mode ...
[62363|1557819587981|22|WARNING    ][UseCase|UseCaseManager.changeUseCase] : No use case transaction found
[62364|1557819589291|22|WARNING    ][UseCase|UseCaseManager.changeUseCase] : No use case transaction found
[62379|1557819589926|22|INFO       ][ErrorManager|ErrorManager.createFortranException] : Type: -1   Message: DALPHA_MULT is not a valid parameter name
[62380|1557819589927|22|INFO       ][Fortran.Error|ErrorManager.createFortranException] : Type: -1   Message: DALPHA_MULT is not a valid parameter name
[62381|1557819589927|22|INFO       ][Fortran.Error|ErrorManager.addMessageToException] : Type: 1   Message: setFieldStringValue => failed
[62382|1557819589927|22|INFO       ][Fortran.Error|ErrorManager.insertMessage] : Type: -1   Message:  
[62383|1557819589927|22|INFO       ][Fortran.Error|ErrorManager.insertMessage] : Type: 3   Message: Invalid value for ParameterGeom['DALPHA'].expression.
Create process abort.
[62384|1557819589934|22|INFO       ][Fortran.Error|ErrorManager.insertMessage] : Type: 3   Message: Error occured while executing the command file :
   1_param_revH.py.
Line : 79.


[62385|1557819589934|22|WARNING    ][ActionManager|UIActionManager.postAction] : Error during action execution: Action: executeSpy Exception: (JavaException, Error occured while executing the command file : 1_param_revH.py. Line : 79. DALPHA_MULT is not a valid parameter name)
Loading new project
Creating ANONYM
... end loading new project
   openModelerContext executed
Modeler context opened
Execution of command file '1_param_revH.py' in batch mode ...
FICHIER PARAM.PY

   ParameterGeom[R_ROT_OUT] created
ParameterGeom[1]
   ParameterGeom[D_MECHGAP] created
   ParameterGeom[D_AGAP] created
   ParameterGeom[D_ST] created
ParameterGeom[4]
   ParameterGeom[R_ST_IN] created
   ParameterGeom[R_ST_OUT] created
   ParameterGeom[D_MOT] created
   ParameterGeom[BETA] created
   ParameterGeom[ALPHA_H] created
   ParameterGeom[ALPHA_CASE] created
   ParameterGeom[H_ST] created
ParameterGeom[11]
   ParameterGeom[H_ROT] created
   ParameterGeom[DTHETA] created

[62580|1557819590936|22|INFO       ][Fortran.Error|ErrorManager.insertMessage] : Type: 3   Message: Error occured while executing the command file :
   C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py.
Line : 28.


[62581|1557819590937|22|WARNING    ][ActionManager|UIActionManager.postAction] : Error during action execution: Action: executeSpy Exception: (JavaException, Error occured while executing the command file : C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py. Line : 28. Error occured while executing the command file : 1_param_revH.py. Line : 79. DALPHA_MULT is not a valid parameter name)
[62743|1557819591037|22|SEVERE     ][Actions|ExecuteCommandAction.doAction] : Error while executing command: Commands: 1 Command: executeBatchSpy('C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py') Exception: (PythonWrapperException, Error occured while executing the command file : C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py. Line : 28. Error occured while executing the command file : 1_param_revH.py. Line : 79. DALPHA_MULT is not a valid parameter name)
[62744|1557819591039|22|WARNING    ][ActionManager|UIActionManager.postAction] : Error during action execution: Action: executeCommandRequest Exception: (JavaException, Can not execute the following command : executeBatchSpy('C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py') Error occured while executing the command file : C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py. Line : 28. Error occured while executing the command file : 1_param_revH.py. Line : 79. DALPHA_MULT is not a valid parameter name)
--------------------------------------------------------------------------------
Anomaly (1) - User error:
Can not execute the following command :
executeBatchSpy('C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py')

Error occured while executing the command file :
   C:/Users/jperalta/Documents/github_pato/flux/2_int_rotor/1_int_rotor_slotless/8_icems_journal_2018_3d/00_main.py.
Line : 28.


Error occured while executing the command file :
   1_param_revH.py.
Line : 79.


DALPHA_MULT is not a valid parameter name
------------------------------ Advanced Text -----------------------------------
setFieldStringValue => failed
Invalid value for ParameterGeom['DALPHA'].expression.
Create process abort.
--------------------------------------------------------------------------------
[62758|1557819591200|19|WARNING    ][IconLoader|DefaultFrontalIconLoader.loadImage] : Icon file does not exist: C:\Program Files\Altair\2018\flux\Flux\Resources/Images/General/Dialog/error.gif
[62759|1557819591202|19|WARNING    ][IconLoader|DefaultFrontalIconLoader.loadImage] : Icon file does not exist: C:\Program Files\Altair\2018\flux\Flux\Resources/Images/General/Dialog/informations.gif
Closing project
Close of ANONYM
[62779|1557819638421|22|WARNING    ][Document|Document.updateInstances] : No project loaded
[62804|1557819638463|22|WARNING    ][Document|Document.updateInstances] : No project loaded
... end closing project
Python : closeProject()

Python : exit()
[62808|1557819638473|22|INFO       ][ExitAction|ExitAction.doAction] : Sending notofication to DB manager
Maximum use of 16 MiB. in numerical memory
For the dynamic table ID 33284
Maximum use of 7 MiB. in character memory
For the dynamic table ID 32300
 
   NUMZM         ADRES    SUIV    PREC    CODE          LONG           UID     PROP4   ...
 
       1             5       6       4   R08 5             0             0
       2             1       5       5   C80 8             0             0
       4     536870913       1       6   R08 5             0             0
       5       1677722       2       2   C80 8             0             0
       6             5       4       1   I04 2        600037             0
Numerical memory: Total length                   = 536870912
(8 byte words)    Present length                 =    600041
                  Useful length                  =    600041
                  Number of numerical arrays     =         3
Character memory: Total length                   =   1677721
(80 byte words)   Present length                 =         0
                  Useful length                  =         0
                  Number of character arrays     =         2
Maximum number of arrays (num+char)              =    100006
 
09:40:38      53 sec. FLUX3D_18.1.0 kernel finalized
[62832|1557819638476|22|INFO       ][ExitAction|ExitAction.doAction] : Closing spy file
[62833|1557819638476|22|INFO       ][ExitAction|ExitAction.doAction] : Closing error tracer
[62834|1557819638476|22|INFO       ][ExitAction|ExitAction.doAction] : Flushing log handlers
